version: '3'


services:
    postgresdb:
        image: postgres:12.0-alpine
        build:
            context: ../docker/postgres
            dockerfile: Dockerfile
        volumes:
            - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
        env_file:
            - ./.env.prod

            
    web:
        build:
            context: ./
            dockerfile: Dockerfile.prod
        command: gunicorn myproject.wsgi:application --bind 0.0.0.0:8000
        ports:
            - 8000:8000 
        volumes:
            - ./:/usr/src/app
        env_file:
            - ./.env.prod
        depends_on:
            - postgresdb
            
            
    nginx:
        build:
            context: ../docker/nginx
        depends_on:
            - web
            - postgresdb
        ports:
            - "80:80"
        volumes:
            - .myproject/static/:/static/