# Generated by Django 3.2.5 on 2021-07-26 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Имя категории')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Категории',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Интерес')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Интерес',
                'verbose_name_plural': 'Интересы',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='bloger',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='фамилия'),
        ),
        migrations.AddField(
            model_name='reader',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='фамилия'),
        ),
        migrations.AddField(
            model_name='reader',
            name='of_age',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bloger',
            name='username',
            field=models.CharField(default=None, max_length=255, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='читатель'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='имя'),
        ),
        migrations.AddField(
            model_name='bloger',
            name='category',
            field=models.ManyToManyField(to='accounts.Category', verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='reader',
            name='interests',
            field=models.ManyToManyField(to='accounts.Interests', verbose_name='Категории'),
        ),
    ]
