# Generated by Django 3.2.5 on 2021-07-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210726_0858'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloger',
            options={'verbose_name': 'Блогер', 'verbose_name_plural': 'Блогеры'},
        ),
        migrations.AlterModelOptions(
            name='reader',
            options={'verbose_name': 'Читатель', 'verbose_name_plural': 'Читатели'},
        ),
        migrations.AlterField(
            model_name='bloger',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='bloger',
            name='country',
            field=models.CharField(default=None, max_length=255, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='bloger',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Электороная почта'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='interests',
            field=models.ManyToManyField(to='accounts.Interests', verbose_name='Интересы'),
        ),
    ]
