# Generated by Django 3.2.5 on 2021-07-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_bloger_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloger',
            name='username',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='имя'),
        ),
    ]
