# Generated by Django 3.2.5 on 2021-07-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_bloger_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloger',
            name='is_super',
            field=models.BooleanField(default=True),
        ),
    ]
