# Generated by Django 3.2.5 on 2021-07-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_bloger_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloger',
            name='status',
            field=models.CharField(choices=[('True', 'bloger'), ('False', 'isn`t bloger')], default='True', max_length=100, verbose_name='are you bloger?'),
        ),
    ]
