# Generated by Django 3.2.6 on 2021-08-06 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210806_1104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloger',
            old_name='avatar',
            new_name='file',
        ),
    ]
