# Generated by Django 3.2.6 on 2021-08-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20210806_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloger',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Электороная почта'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='interests',
            field=models.ManyToManyField(blank=True, to='accounts.Interests', verbose_name='Интересы'),
        ),
    ]
