# Generated by Django 3.2.6 on 2021-08-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20210811_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloger',
            name='category',
            field=models.ManyToManyField(null=True, to='accounts.Category', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='interests',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.Interests', verbose_name='Интересы'),
        ),
    ]
