# Generated by Django 3.2.5 on 2021-07-27 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['-pk'], 'verbose_name': 'Доска', 'verbose_name_plural': 'Доски'},
        ),
    ]
