# Generated by Django 3.2.6 on 2021-08-03 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20210803_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='photo',
        ),
        migrations.AddField(
            model_name='photo',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='boards.topic'),
            preserve_default=False,
        ),
    ]
