# Generated by Django 3.2.6 on 2021-08-05 12:32

from django.db import migrations
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_alter_photo_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=smartfields.fields.ImageField(upload_to=''),
        ),
    ]
