# Generated by Django 3.2.6 on 2021-08-05 12:34

from django.db import migrations
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_alter_photo_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='file',
        ),
        migrations.AddField(
            model_name='photo',
            name='avatar',
            field=smartfields.fields.ImageField(default=1, upload_to='avatar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='avatar_jpeg',
            field=smartfields.fields.ImageField(default=1, upload_to='avatar'),
            preserve_default=False,
        ),
    ]
