# Generated by Django 3.2.6 on 2021-08-05 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_auto_20210805_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='avatar_jpeg',
            new_name='photo',
        ),
    ]
