# Generated by Django 3.2.6 on 2021-08-09 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_auto_20210805_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_activ',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
