# Generated by Django 3.2.6 on 2021-08-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0009_topic_is_activ'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='is_activ',
        ),
        migrations.AddField(
            model_name='board',
            name='is_activ',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalboard',
            name='is_activ',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
